#!/bin/bash

# Cabeçalho
# ----------------------------------------------------------------------------
# Esqueleto de Script.
# Script feito para gerar uma especie de casca de script, facilitando na hora da criação de um script novo
#
# Uso: ./esqueleto <nome_do_novo_script>
# Ex.: ./esqueleto dummy_script
#
# Autor: Frank Junior <frankcbjunior@gmail.com>
# Desde: 2013-12-24
# Versão: 1
# ----------------------------------------------------------------------------

# Configurações
# ----------------------------------------------------------------------------

# set:
# -e: se encontrar algum erro, termina a execução imediatamente
set -e

# import da lib_alfred
if [ -z "$LIB_ALFRED" ];then
	echo '[ERRO] provalvelmente, a $LIB_ALFRED nao foi instalada'
	exit 1
else
	source "$LIB_ALFRED"
fi

# Variáveis
# ----------------------------------------------------------------------------
nome_do_script="$1"
readme="README.md"
nome_do_usuario=""
email_do_usuario=""
lib='$LIB_ALFRED'
debug='$DEBUG'

# DEBUG = 0, desligado
# DEBUG = 1, ligado
DEBUG=0


# Funcoes
# ----------------------------------------------------------------------------

# funcao de debug
function debug(){
	[ "$DEBUG" = 1 ] && echo "[DEBUG] $*"
}

function validacoes(){
	# se não passar nenhum parametro, dá erro
	if [ "$nome_do_script" == "" ];then
		lib_alfred-print_erro "# Uso: ./esqueleto <nome_do_novo_script>"
		lib_alfred-print_erro "# Ex.: ./esqueleto dummy_script"
		exit 1
	fi

	# verificando se o script já foi criado
	if [ -d $nome_do_script ]; then
		lib_alfred-print_erro "Script já existe com esse nome"
		exit 1
	fi

	# pegando as configurações do git para preencher o cabeçalho.
	if [ $(which git > /dev/null; echo $?) == "0" ];then
		email_do_usuario="$(cd ~; git config --list | grep "user.email" | cut -d "=" -f2; cd - > /dev/null)"
		nome_do_usuario="$(cd ~; git config --list | grep "user.name" | cut -d "=" -f2; cd - > /dev/null)"
	# se não tiver git instalado ,coloque o nome do usuario corrente no script, 
	# e coloque um TODO no email
	else
		nome_do_usuario=$(whoami)
		email_do_usuario="TODO: email@email.com"
	fi
}

# Função que cria as linhas do script
function criar_script(){
	
echo "#!/bin/bash

# Cabeçalho
# ----------------------------------------------------------------------------
# TODO: Descrição...
#
# Uso:
# Ex.: 
#
# Autor: $nome_do_usuario <$email_do_usuario>
# Desde: $(date +%Y-%m-%d)
# Versão: 1
# ----------------------------------------------------------------------------

# Configurações
# ----------------------------------------------------------------------------

# set:
# -e: se encontrar algum erro, termina a execução imediatamente
set -e

# import da lib_alfred
if [ -z \"$lib\" ];then
	echo '[ERRO] provalvelmente, a $lib nao foi instalada'
	exit 1
else
	source \"$lib\"
fi

# Variáveis
# ----------------------------------------------------------------------------

# DEBUG = 0, desligado
# DEBUG = 1, ligado
DEBUG=0

# Funções
# ----------------------------------------------------------------------------

# funcao de debug
function debug(){
	[ \"$debug\" = 1 ] && echo \"[DEBUG] $*\"
}

function validacoes(){

# TODO validacoes aqui...
echo \"\"

}

# Main
# ----------------------------------------------------------------------------

validacoes

# codigo aqui...

# TODO: trocar essa mensagem
lib_alfred-print_success \"Ola, meu nome eh \"$nome_do_script\"\"

" > "$nome_do_script"
}

# função que cria as linhas do README.md
function criar_readme(){
	
echo "$nome_do_script
===========

## Descrição

## Dependências
* [**lib_alfred**](https://github.com/frankjuniorr/lib_alfred)

## Uso
Uso: \`./"$nome_do_script"\`

Ex: \`./"$nome_do_script"\`
" > "$readme"
}

# versionar o script com o git
function git_init(){


	if [ $(which git > /dev/null; echo $?) == "0" ];then
		echo "*~" > .gitignore
		git init > /dev/null
		git add "$readme" "$nome_do_script" .gitignore
		git commit -m "criado o esqueleto do $nome_do_script" > /dev/null
	fi

}

# Main
# ----------------------------------------------------------------------------

validacoes

# criando o diretorio do script
mkdir "$nome_do_script"

# entrando no diretorio do script
cd "$nome_do_script"

# criando um arquivo em branco com o nome do script
touch "$nome_do_script"

# dando permissão de execução pro script
chmod +x "$nome_do_script"

criar_script
criar_readme
git_init

lib_alfred-print_success "script "$nome_do_script" criado com sucesso"

